### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cattard1985** [Taapat/enigma2-plugin-youtube#72] opened 2020-04-10 20:45 UTC
I am receiving this error"there  was an error in creating entry list! maybe try other feeds" as i click on a searched item. Using vu+ zero, open atv 6.4 enigma 2

**Comment by Taapat** [comment] 2020-04-11 12:06
The problem is with the YouTube Data API keys quota.
Please create and use your own keys: https://github.com/Taapat/enigma2-plugin-youtube/issues/67

**Comment by Taapat** [comment] 2020-07-09 13:06
The YouTube Data API keys quota is now sufficient.
I think I can close this issue.

**Closed by Taapat** 2020-07-09 13:06 UTC
